#!/usr/bin/env python3

import os
import argparse

def log(message):
    print(f"\n\033[92m[THRNIX] >> \033[97m{message}\033[0m\n")

def update(target):
    log("Updating NixOS")
    os.system("sudo nixos-rebuild switch --flake /etc/nixos")

    match target:
        case "user":
            log("Updating User Home-Manager")
            os.system("home-manager switch --flake /etc/nixos")
        case "system":
            log("Updating Every User Home-Manager")
            os.system("""
                for user in $(awk -F: '($3 >= 1000 && $1 !~ /^(nixbld|nobody|rescue)/) {print $1}' /etc/passwd); do 
                    sudo -u "$user" echo "[THRNIX] >> User $user loading..."; nix run nixpkgs#home-manager -- switch --flake /etc/nixos;
                done
            """)

parser = argparse.ArgumentParser( description="THRNix management script")
subparsers = parser.add_subparsers(dest="command")

update_parser = subparsers.add_parser("update", help="Update system")
update_parser.add_argument("target", choices=["user", "system"])

args = parser.parse_args()

match args.command:
    case "update": update(args.target)
    case _: parser.print_help()
